[Log]
# AlertKeywords це ключові слова що програма шукає в логах. Якщо вони знайдені, то відправляється повідомлення в телеграм
AlertKeywords = ["1SIG", "4SHP", "2SND", "3MOV"]
# LogPath це шлях до логів. Крапка означає поточну директорію (де знаходиться програма)
Path = "."
[Telegram]
# Token це токен бота, його потрібно отримати створивши бота у https://t.me/BotFather
Token = "1234567890:ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
# ChatId це ідентифікатор чату, в який будуть відправлятися повідомлення. Його можна отримати у https://t.me/myidbot
ChatId = 123456789
# MessageTemplate це шаблон повідомлення, яке буде відправлено у телеграм.
# Його можна підредагувати, як вам буде зручніше.
# Шаблон може містити наступні змінні:
# {{.Keyword}} - ключове слово, яке було знайдено
# {{.File}} - файл, в якому було знайдено ключове слово
# {{.String}} - строчка, в якій було знайдено ключове слово
MessageTemplate = "Увага, з'явилося ключеве слово {{.Keyword}} в файлі {{.File}} в строчці: {{.String}}"
